### ISSUE TITLE
myid should be in the data directory

### ISSUE THREAD

**Issue by p-hu** [deric/puppet-zookeeper#10]
The [zookeeper docs](http://zookeeper.apache.org/doc/r3.4.6/zookeeperAdmin.html#sc_zkMulitServerSetup) say the `myid` file should be in the dataDir but in `config.pp` `myid` is placed in the config directory
```puppet
  file { "${cfg_dir}/myid":
    ensure  => file,
    content => template('zookeeper/conf/myid.erb'),
    owner   => $user,
    group   => $group,
    mode    => '0644',
    require => File[$cfg_dir],
    notify  => Class['zookeeper::service'],
  }
```
Is this intentional or by accident? I haven't been able to get a multiserver setup working with myid in the config directory.

**Comment by deric** [comment]
Which distribution do you use? (package from Cloudera or OS native?)

**Comment by p-hu** [comment]
OS native

**Comment by deric** [comment]
Ok, and which distribution?

**Comment by p-hu** [comment]
zookeeper-3.4.6 for centos packaged as an rpm

**Comment by p-hu** [comment]
nice, thanks!
