### ISSUE TITLE
systemd service file problem with CLASSPATH

### ISSUE THREAD

**Issue by denys-mazhar-rp** [deric/puppet-zookeeper#101]
Hi! The cloudera RPM package with zookeeper (version 3.4.5+cdh5.12.0+112) has this inside the `/usr/lib/zookeeper/bin/zkEnv.sh` file:
```bash
if [ -f "$ZOOCFGDIR/java.env" ]
then
    . "$ZOOCFGDIR/java.env"
fi
```
This resolves into the `/etc/zookeeper/conf/java.env` file, which is created by puppet-zookeeper module. It has this line:
```bash
CLASSPATH="$ZOOCFGDIR:/usr/share/java/jline.jar:/usr/share/java/log4j-1.2.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xmlParserAPIs.jar:/usr/share/java/netty.jar:/usr/share/java/slf4j-api.jar:/usr/share/java/slf4j-log4j12.jar:/usr/share/java/zookeeper.jar"
```
So it overwrites the CLASSPATH and removes the folder added by systemd service file:
```bash
  CLASSPATH="/usr/lib/zookeeper/zookeeper.jar:/usr/lib/zookeeper/lib/*:$CLASSPATH"; \
```
This results in buggy systemd service file, so it is impossible to start the zookeeper. Getting the error:
```
Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
```
This is the CLASSPATH that is the result of all that include and substitutions: `CLASSPATH='/usr/bin/../build/classes:/usr/bin/../build/lib/*.jar:/usr/bin/../lib/*.jar:/usr/bin/../zookeeper-*.jar:/usr/bin/../src/java/lib/*.jar:/etc/zookeeper/conf:/etc/zookeeper/conf:/usr/share/java/jline.jar:/usr/share/java/log4j-1.2.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xmlParserAPIs.jar:/usr/share/java/netty.jar:/usr/share/java/slf4j-api.jar:/usr/share/java/slf4j-log4j12.jar:/usr/share/java/zookeeper.jar'`

The easiest way should be to fix the java.env file, as it is managed by puppet module. So it'll not overwrite the CLASSPATH.

**Comment by deric** [comment]
Should be resolved by #102.
