### ISSUE TITLE
zookeeper does not start under debian stretch - invalid environment file

### ISSUE THREAD

**Issue by jeromedrouet** [deric/puppet-zookeeper#109]
generated environment file does not work for debian strech /systemd launch

variables are not taken into account, leading java process to be launched with variable names instead of content, for instance '$ZOOCFGDIR/zoo.cfg'

real fix : use systemd environment variables (is hardcoding them into service script better than in config file ? ;-) )

current fix : see attached patch to remove variable references in environment : $CLASSPATH and $ZOOCFGDIR

works fine with 0.7.5 and this patch on debian stretch amd64

**Comment by jeromedrouet** [comment]
[0001-fix-environnement-variables-for-stretch-systemd.patch.txt](https://github.com/deric/puppet-zookeeper/files/1474255/0001-fix-environnement-variables-for-stretch-systemd.patch.txt)

**Comment by deric** [comment]
Thanks!

**Comment by zlanyi** [comment]
Hi,
could you please add a new tag with this fix?

Thanks

regads,
Zoltan

**Comment by deric** [comment]
Sure, tagged as [v0.7.6](https://github.com/deric/puppet-zookeeper/releases/tag/v0.7.6).

**Comment by zlanyi** [comment]
thanks a lot :)
