### ISSUE TITLE
[UBUNTU 14.04] Could not find init script or upstart conf file for 'zookeeper'

### ISSUE THREAD

**Issue by cesarpball** [deric/puppet-zookeeper#111]
When I use ubuntu 14.04 and 'upstart' as service provider, the init script is not created, so puppet fails.

Then, If I select other provider, the script is created but not working.

This is my conf:
```puppet
class { '::zookeeper':
      id                   => $_id,
      servers              => $_servers,
      install_java         => true,
      java_package         => $java_package,
      packages             => ['zookeeper', 'zookeeperd'],
      service_name         => 'zookeeper',
      initialize_datastore => false,
      manage_service_file  => true,
      service_provider     => 'upstart',
      install_method       => 'archive',
      archive_version      => '3.4.11',
      archive_install_dir  => '/opt',
      ensure_cron          => false,
      snap_retain_count    => '5',
      purge_interval       => '3',
      restart_on_change    => false
    }
```

I think that we are missing on `puppet-zookeeper/manifests/service.pp` line 20 the provider upstart?
We are using upstart instead of systemd
Using ubuntu 14.04

Thanks

**Comment by deric** [comment]
Hi @cesarpball, yes you're right. The typical use-case is that service manifest (init.d, systemd file, ..) is provided with OS package. In you case there's no upstart manifest. What should it look like?
Btw. you should be able to use `init` script on Ubuntu 14.04 as well.

**Comment by cesarpball** [comment]
Hi @deric ,

Sorry for my late response. Using **init** didn't work as expected, so I added a template to the init.d file to manage the service.

Thanks for your help

**Comment by deric** [comment]
No problem. @cesarpball If there's some reusable piece of code, please create a PR.
