### ISSUE TITLE
Fails on empty $::domain

### ISSUE THREAD

**Issue by mszymo** [deric/puppet-zookeeper#117]
Ubuntu 16.04 LTS
Puppet version 5.5.6

If the server has no domain set up (meaning the trusted fact $::domain is empty) then the module fails on params.pp L 150. This is because $realm = $::domain, and cannot handle if it is empty. Changing it to $realm = 'local.domain' allows the module to run correctly. Seems to be only used for the Jaas stuff?

**Comment by rmalenko** [comment]
We are using full domain name in puppet agent configuration sow we can use 
`$trusted['certname']`

**Comment by deric** [comment]
@rmalenko The value would be slightly different `$::domain` would return `example.com` whereas `$trusted['certname']` would be something like `web01.example.com`. But as long as it is just default value that can be overwritten we should avoid errors like this.

**Comment by deric** [comment]
Resolved in [v0.8.5](https://github.com/deric/puppet-zookeeper/releases/tag/v0.8.5)
