### ISSUE TITLE
Dependency issue while upgrading deric-zookeeper

### ISSUE THREAD

**Issue by bsingh27** [deric/puppet-zookeeper#118]
Hi Deric,

I'm trying to upgrade deric-zookeeper from (v0.7.2 -> v0.8.0) and seeing below error. Can you please help here

[root@puppet1-0.vagrant.com bharaths]# puppet module upgrade deric-zookeeper --modulepath=/etc/puppetlabs/code/environments/bharaths/site
Notice: Preparing to upgrade 'deric-zookeeper' ...
Notice: Found 'deric-zookeeper' (v0.7.2) in /etc/puppetlabs/code/environments/bharaths/site ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'deric-zookeeper' (v0.7.2 -> latest)
  There are 6 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    - puppet-archive
    - puppetlabs-pe_gem
    - richardc-datacat
    Use `puppet module upgrade --force` to upgrade only this module

**Comment by deric** [comment]
Hi, dependencies of this module are listed in [`metadata.json`](https://github.com/deric/puppet-zookeeper/blob/master/metadata.json#L14)
```
    {
      "name": "puppetlabs/stdlib",
      "version_requirement": ">= 2.3.3 < 5.0.0"
    },
    {
      "name": "puppet/archive",
      "version_requirement": ">= 0.4.4 < 3.0.0"
    }
```
Could you please check which versions of `puppetlabs-stdlib` and `puppet-archive` you're trying to upgrade to?

**Comment by bsingh27** [comment]
puppetlabs-stdlib (v4.18.0)
puppet-archive (v1.0.1-rc0)

**Comment by deric** [comment]
You're probably trying to upgrade to newer versions, e.g. `puppetlabs-stdlib == 5.0`. The version constraint should be fixed by #116. I'll try to prepare a new release.

**Comment by bsingh27** [comment]
After upgrading stdlib to latest version ( 5.1 ) I was able to upgrade zookeeper, but when am trying to install on one of the client box through puppet agent, I see below error

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Zookeeper]: parameter 'id' expects a String value, got Integer at /etc/puppetlabs/code/environments/bharaths/site/profiles/manifests/zookeeper.pp:16:3 on node vl1zookeeper1-0.bharaths.local.vm

I see $id is referring to String rather Integer in zookeeper/manifests/init.pp, hence its complaining. Any thoughts ??
I tried renaming String to Integer and it worked. But am not sure if that is the right way to do. Please suggest

**Comment by deric** [comment]
Dependency problem should be solved in latest release. How do you set `id`?
```
zookeeper::id: '1'
```
The parameter value should be quoted.

**Comment by bsingh27** [comment]
I'm using 
$myid      = regsubst($::appnode,'^.*-(\d*)$','\1') + 1  # ( which returns integer value `1` )
class { 'zookeeper':
 id                   => $myid,
}

**Comment by deric** [comment]
Right, the integer value is the problem. 
```puppet
$myid = regsubst($::appnode,'^.-(\d)$','\1') + 1
class { 'zookeeper':
  id => "${myid}
}
```
Moving forward it might be good idea to convert the ID to integer type.
 I'm closing the issue, as the dependency problem seems to be solved.
