### ISSUE TITLE
upgrade to zookeeper version 3.4.11

### ISSUE THREAD

**Issue by bsingh27** [deric/puppet-zookeeper#119]
Hi Deric,

I'm trying to upgrade zookeeper version from 3.4.5 to 3.4.11. I have upgraded puppet module deric-zookeeper to latest version, still seeing zookeeper version as 3.4.5 and I'm not sure how to upgrade zookeeper version to 3.4.11 I tried with below code but it didn't help. Can you please guide here

```puppet
  class { 'zookeeper':
    datastore            => '/u001/zookeeper',
    election_port        => 2889,
    leader_port          => 3889,
    servers                 => $servers,
    id                           => "${myid}",
    packages              => ['zookeeper', 'zookeeper-server'],
    archive_version      => '3.4.11',
    service_name         => 'zookeeper-server',
    initialize_datastore => true,
    repo                 => 'cloudera',
    cdhver               => '5',
```

**Comment by bsingh27** [comment]
here is the version currently installed
[root@vl1zookeeper1-0 zookeeper]# rpm -qa | grep zoo
zookeeper-3.4.5+cdh5.15.1+149-1.cdh5.15.1.p0.4.el6.x86_64
zookeeper-server-3.4.5+cdh5.15.1+149-1.cdh5.15.1.p0.4.el6.x86_64

**Comment by deric** [comment]
It looks like you're missing the option
```puppet
install_method => 'archive',
```
by default, a `package` value is used, which installs `$packages` from system's distribution.

**Comment by bsingh27** [comment]
Deric... it worked !!!! thanks so much.. Am closing the ticket
