### ISSUE TITLE
Remove the require function from config.pp

### ISSUE THREAD

**Issue by PierreR** [deric/puppet-zookeeper#124]
Do you really need this require/include ? 
https://github.com/deric/puppet-zookeeper/blob/800fbe2e73b1df07e63d7589a4b22ebba921474b/manifests/config.pp#L7

I guess this is  because you initialize the datastore at the end of the file ? Still the order is already managed in `init.pp` and I am wondering (knowing nothing about zookeeper per se) if this initialization really belongs in a config.pp file.

Anyhow this is annoying for use, because we use a [testing tool](https://github.com/bartavelle/language-puppet) that prohibits the usage of the `require` function. When we really need it we prefer chaining Class with `->`.

Thanks for your support !

**Comment by deric** [comment]
I think the `require` statement is redundant in this case, as we already have chaining `->` [in here](https://github.com/deric/puppet-zookeeper/blob/master/manifests/init.pp#L126)
