### ISSUE TITLE
Does not create folders for datastore and datalogstore

### ISSUE THREAD

**Issue by rmalenko** [deric/puppet-zookeeper#126]
Hi,
I have got message 
```
Error: Could not set home on user[zookeeper]: Execution of '/usr/sbin/usermod -d /data/zookeeper zookeeper' returned 8: usermod: user zookeeper is currently used by process 3122
Error: /Stage[main]/Zookeeper/User[zookeeper]/home: change from '/var/lib/zookeeper' to '/data/zookeeper' failed: Could not set home on user[zookeeper]: Execution of '/usr/sbin/usermod -d /data/zookeeper zookeeper' returned 8: usermod: user zookeeper is currently used by process 3122
```
I think it because does not create folders for `datastore` and `datalogstore`
/data/zookeeper and `/datalog/zookeeper`

```
node /^zookeeper-([0-9][0-9][0-9])\.tests\.biz$/ {

  class { 'zookeeper':
    packages                => ['zookeeper'],
    initialize_datastore    => true,
    service_name            => 'zookeeper-server',
    election_port           => 2889,
    leader_port             => 3889,
    servers                 => ['zookeeper-001.tests.biz', 'zookeeper-002.tests.biz', 'zookeeper-003.tests.biz'],
    # observers             => ['zookeeper-003.tests.biz'],
    service_provider        => 'systemd',
    manage_service_file     => true,
    systemd_unit_after      => 'network-online.target',
    systemd_unit_want       => 'network-online.target',
    console_threshold       => 'INFO',
    rollingfile_threshold   => 'INFO',
    tracefile_threshold     => 'TRACE',
    maxfilesize             => '256MB',
    maxbackupindex          => 10,
    tick_time               => 2000,
    init_limit              => 30000,
    sync_limit              => 10,
    max_allowed_connections => 2000,
    max_session_timeout     => 60000000,
    datastore               => '/data/zookeeper',
    datalogstore            => '/datalog/zookeeper',
    snap_retain_count       => 10,
    purge_interval          => 1,
    snap_count              => 3000000,
    leader                  => true,
  }
}

**Comment by deric** [comment]
Which OS/distribution do you use?

From `man usermod`:

```
CAVEATS
       You must make certain that the named user is not executing any processes when this command is being executed if the user's numerical user
       ID, the user's name, or the user's home directory is being changed.  usermod checks this on Linux, but only check if the user is logged in
       according to utmp on other architectures.
```
If `zookeeper` service is being executed by `zookeeper` user, `cat /etc/passwd | grep zoo`:

```
zookeeper:x:109:116:Zookeeper:/var/lib/zookeeper:/bin/false
```
with shell set to `/bin/false` this shouldn't happen. I guess you're running `zookeeper` service under `root` and then `usermod` is refusing to work. Is that assumption correct?

**Comment by rmalenko** [comment]
Thank you for your answer. You are right.

I use Debian 9
`zookeeper:x:1707:1707:Zookeeper:/data/zookeeper:/bin/false`

I have stopped the zookeeper and checked if it isn't present in memory
and then run `puppet agent --test`
but the directory wasn't created `/data/zookeeper`

The new error message appeared: `Error: Cannot create /data/zookeeper; parent directory /data does not exist`

I am a newbie in Puppet and I am not sure but may something like this should use?

```
file { [ '/data',
         '/data/zookeeper',]:
           ensure => directory,
           ...
}
```

**Comment by deric** [comment]
@rmalenko Puppet newbies sometimes struggle with "randomness" of a Puppet statement. Puppet code isn't typical sequential language, each statement needs to declare all of its dependencies. It's a powerful concept that allows parallel execution, thus allowing faster Puppet runs. 

The code above can be rewritten:
```puppet
  file { '/data':
    ensure  => directory,
  }

  file { '/data/zookeeper':
    ensure  => directory,
    require => File['/data'],
  }
```
alternatively you could use:
```puppet
  file { '/data/zookeeper':
    ensure  => directory,
    recurse => true,
  }
```
Generally the first approach is preferred, as recursive operations on filesystem might take too long (#41) - this might be problem when you start changing ownership and permissions of the file resource.

Your code above could be rewritten as:

```puppet
  class { 'zookeeper':
    datastore      => '/data/zookeeper',
    datalogstore => '/datalog/zookeeper',
    require          => [File['/data'], File['/datalog']],
   ...
  }  
  file { '/data':
    ensure  => directory,
  }

  file { '/datalog':
    ensure  => directory,
  }
```
Directory `/data/zookeeper` will be created using this [module's code](https://github.com/deric/puppet-zookeeper/blob/master/manifests/config.pp#L24). The statement `require       => File['/data'],` will ensure appropriate execution order.

I'm closing the issue, as there's not much we can improve on code of this module.
