### ISSUE TITLE
Seems like there is no way to set zookeeper globalOutstandingLimit

### ISSUE THREAD

**Issue by ofer-velich** [deric/puppet-zookeeper#128]

**Comment by deric** [comment]
@ofer-velich implemented in 3a16b7329ceaccf0fcdd25b143ee47945a2fcfb1, should be part of next release:
```puppet
class{'zookeeper':
  global_outstanding_limit => 5000
}
```

**Comment by deric** [comment]
Released in [v0.8.7](https://github.com/deric/puppet-zookeeper/releases/tag/v0.8.7).
