### ISSUE TITLE
Add whitelist commands in zoo.cfg

### ISSUE THREAD

**Issue by swmadmsys** [deric/puppet-zookeeper#135]
Please add a variable to manage whitelist commands in configuration file  zoo.cfg

From [https://zookeeper.apache.org/doc/r3.4.12/zookeeperAdmin.html](https://zookeeper.apache.org/doc/r3.4.12/zookeeperAdmin.html)
> 4lw.commands.whitelist
> (Java system property: zookeeper.4lw.commands.whitelist)
> 
> New in 3.4.10: This property contains a list of comma separated Four Letter Words commands. It is introduced to provide fine grained control over the set of commands ZooKeeper can execute, so users can turn off certain commands if necessary. By default it contains all supported four letter word commands except "wchp" and "wchc", if the property is not specified. If the property is specified, then only commands listed in the whitelist are enabled.
> 
> Here's an example of the configuration that enables stat, ruok, conf, and isro command while disabling the rest of Four Letter Words command:
> 
>                 4lw.commands.whitelist=stat, ruok, conf, isro
>               
> Users can also use asterisk option so they don't have to include every command one by one in the list. As an example, this will enable all four letter word commands:
> 
>                 4lw.commands.whitelist=*
>

**Comment by deric** [comment]
Implemented and released in [v0.8.6](https://github.com/deric/puppet-zookeeper/releases/tag/v0.8.6).
