### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by dhoppe** [deric/puppet-zookeeper#142]
Hello Thomas, 

is this module still maintained? 

For example, Puppet 3 is still supported, although Puppet 4 is already obsolete:
* https://puppet.com/docs/puppet/4.10/release_notes.html

But the support for Puppet 6 is still missing:
* https://github.com/deric/puppet-zookeeper/issues/132

If interested, I would like to create a few pull requests to clean up. 

If the module is no longer maintained, I would be happy about a migration to Vox Pupuli:
* https://voxpupuli.org/docs/migrate_module

Kind regards
Dennis

**Comment by deric** [comment]
Hi Dennis, yes it's still maintained. I didn't have time to test all changes properly. I'll be happy for help. Thanks!
