### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by dhoppe** [deric/puppet-zookeeper#150]
@deric Could you please push a new release to the Puppet Forge? According to the breaking changes, this should be a major release.

**Comment by deric** [comment]
Sure, if you're done with the PRs, we can make a release.

**Comment by deric** [comment]
`v1.0.0` release is on Puppet Forge. Deploy via Travis didn't work, it might be a blacksmith issue, I didn't have time to investigate.

**Comment by dhoppe** [comment]
The password is missing:
https://github.com/deric/puppet-zookeeper/blob/master/.travis.yml#L92

You added it at .sync.yml, but this would require a msync update, to add it to .travis.yml.

**Comment by deric** [comment]
Shouldn't be `modulesync` included in `Gemfile`?

**Comment by dhoppe** [comment]
Not exactly, because a different repository is required:
* https://github.com/voxpupuli/modulesync_config
