### ISSUE TITLE
zookeeper 3.5.5 - Download

### ISSUE THREAD

**Issue by MrMunki** [deric/puppet-zookeeper#151]
Hi,

It seems the logic is not correct in the archive.pp to work out the location of the download for zookeeper. 3.5.5 has moved to the archive section since newer versions have been released. I'm currently using 3.5.5 and no longer downloads as expected. Would it be simpler to move all downloads to the archive site as this appears to hold all versions not just old versions (stable and current are on this site too).

Tried using the archive_dl_url setting but I don't seem to be able to get it to work (it still tries to download from the same location).

http://apache.org/dist/zookeeper/zookeeper-3.5.5/apache-zookeeper-3.5.5-bin.tar.gz - this is the link created by puppet.

It should be

http://archive.apache.org/dist/zookeeper/zookeeper-3.5.5/apache-zookeeper-3.5.5-bin.tar.gz

**Comment by deric** [comment]
Hi @MrMunki,

the change has been introduced in #129, feel free to submit a PR. Maybe the URL has changed?

**Comment by MrMunki** [comment]
So the URL has changed, I'll assume at the time of writing 3.5.5 was the latest version maybe? Now 3.5.8 is available on a similar url, not 3.5.5. Looks to be a moving target so using the archive site would be easier.

**Comment by MrMunki** [comment]
I missed the 'archive_dl_site' setting that was available, setting that fixed my issue.
