### ISSUE TITLE
Feature request: add ability to not manage yum repo file

### ISSUE THREAD

**Issue by voiprodrigo** [deric/puppet-zookeeper#153]
Hi,

I need to use a custom internal repo. That repo is already setup by another module that is central to my infrastructure.
However, I don't see a way to make it so that the zookeeper module does not deploy a repo file (may be there though, if so appreciate a pointer)

Thanks!

**Comment by voiprodrigo** [comment]
By the way, this is because at some point the default for $repo became 'cloudera' instead of undef. It was a very good default for my particular case.

**Comment by deric** [comment]
The possibility to configure custom repository was originally introduced in #40 with `$repo` set to `undef`. Having sane defaults is definitely a good idea. The change has been made in [this commit](https://github.com/deric/puppet-zookeeper/pull/146/commits/1684d91fb4b88eaa81f8d2af71ba168047aea772) as part of large refactoring #146. I'm sorry I didn't catch this.

@dhoppe is it ok to revert this change?

Pinpointing to specific release should be done for certain OS release, not globally.

**Comment by dhoppe** [comment]
@deric Sounds reasonable. I was not thinking about private repositories at all.

**Comment by evgenkisel** [comment]
Hello! Where are you going to deliver fixes to disable the problem with setting up Cloudera repo by default?
Also I tried to change a value for the variable $repo in Hiera, but it doesn't work.

**Comment by MrMunki** [comment]
It seems like the cloudera repo is not available, which causes the puppet run to fail any yum installs. I don't use the repo and download a custom version of zookeeper, is it possible to disable the repo all together? I had a look at the code and it seems that the "enabled => 1" option is hard coded on the custom repo, everything else is a variable, is it possible to set a variable on this too? That would work for the removal of the repo, just disable it.

**Comment by deric** [comment]
In `v1.1.0` Cloudera repo is completely removed, `$repo` defaults to `undef`.
