### ISSUE TITLE
install_method set to archive should not try and install the repository

### ISSUE THREAD

**Issue by volfco** [deric/puppet-zookeeper#160]
I'm running CentOS 8, which isn't supported by Cloudera ... yet, but there is a hard fail in the module even when install_method is not set to archive.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Yum repository 'cloudera' is not supported for redhat version 8 
```

It doesn't make sense that if install_method is archive, the repository should not be attempted to be installed.

**Comment by deric** [comment]
I'm not sure which version you're using. This was partially addressed by #153, which unfortunately hasn't been released yet.
