### ISSUE TITLE
Cloudera repo not available

### ISSUE THREAD

**Issue by MrMunki** [deric/puppet-zookeeper#167]
Hi, I posted in another open issue about the cloudera repo, it seems this is now behind a paywall so it's not working at all and with the current config it will never work. Is it worth changing to the archive based deployment excusively? I've been using it for over a year and it works well. Apart from the hard coded repo that is.

**Comment by deric** [comment]
Sure, please submit it as a PR. Thanks!

**Comment by deric** [comment]
Thanks for bringing this up, I've removed Cloudera support and now only `$repo` config as `Hash` is accepted. Eventually we might support configuring Cloudera via this config (if we pass somehow username and password).
