### ISSUE TITLE
Enable TLS / params for ssl.keyStore / ssl.trustStore

### ISSUE THREAD

**Issue by linuxmail** [deric/puppet-zookeeper#175]
Hello,

maybe I do not see it .. but is it possible to enable TLS  params and tell, where to store / find ssl.keyStore / ssl.trustStore ?

cu denny

**Comment by linuxmail** [comment]
hi,

it seems, that required params does not exists. Will send later a patch to add it.

**Comment by deric** [comment]
@linuxmail No, not yet.

I guess also password should be configurable:
```
zookeeper.ssl.keyStore.location="/path/to/your/keystore"
zookeeper.ssl.keyStore.password="keystore_password"
zookeeper.ssl.trustStore.location="/path/to/your/truststore"
zookeeper.ssl.trustStore.password="truststore_password"
```
Ideally add it to the [config template](https://github.com/deric/puppet-zookeeper/blob/master/templates/conf/zoo.cfg.erb).

**Comment by linuxmail** [comment]
hi @deric 

did it already .. just need to cleanup.
