### ISSUE TITLE
SSL configuration in new release

### ISSUE THREAD

**Issue by ydelanoe** [deric/puppet-zookeeper#178]
Hi
Not sure if this is the good place to ask, but would it be possible to have a new release of the module including SSL configuration features added in November 2021 ?

Thank you
Best, 
Yd

**Comment by deric** [comment]
Released as [v1.3.0](https://github.com/deric/puppet-zookeeper/releases/tag/v1.3.0).

**Comment by ydelanoe** [comment]
Thank You !
