### ISSUE TITLE
Bad keystore_quorum_type param used for truststore type

### ISSUE THREAD

**Issue by ydelanoe** [deric/puppet-zookeeper#179]
Hi

In quorum tls configuration, quorum keystore type param is used instead of truststore type parameter here :
https://github.com/deric/puppet-zookeeper/blob/b2b1169c24be5e78ea384c1bdc24e810b044c3c7/templates/conf/zoo.cfg.erb#L198
It should use this parameter:
https://github.com/deric/puppet-zookeeper/blob/dd77962d4571a04290220a00e552a77c4c4950fb/manifests/params.pp#L148

Same for ssl.trustStore.type that should be filled with truststore_type parameter instead of keystore type:
https://github.com/deric/puppet-zookeeper/blob/b2b1169c24be5e78ea384c1bdc24e810b044c3c7/templates/conf/zoo.cfg.erb#L173

Still in TLS configuration, there is a typo on zoo.cfg.erb on keystore_quorum_password (keystore_keystore_quorum_password instead of keystore_quorum_password ) parameter:
https://github.com/deric/puppet-zookeeper/blob/a4c2a5ff6e6cf90dfe29dc510c17836787c572fa/templates/conf/zoo.cfg.erb#L194

**Comment by ydelanoe** [comment]
I've created a PR 
https://github.com/deric/puppet-zookeeper/pull/180

**Comment by deric** [comment]
Fixed in #180.
