### ISSUE TITLE
Add official Puppet 8 support

### ISSUE THREAD

**Issue by der-eismann** [deric/puppet-zookeeper#193]
From our experience the module works fine with Puppet 8, a0bf6098c422d708c4e2e9fdfddf1d3fd06beb79 also included tests for it, so why not [mark it compatible](https://github.com/deric/puppet-zookeeper/blob/master/metadata.json#L77)? :slightly_smiling_face:

**Comment by der-eismann** [comment]
Mega, thanks!

**Comment by deric** [comment]
@der-eismann No problem :slightly_smiling_face:  The new version is tagged as [`v1.5.0`](https://github.com/deric/puppet-zookeeper/releases/tag/v1.5.0).
