### ISSUE TITLE
Adjust dependency between config and service modules

### ISSUE THREAD

**Issue by stephanmitchev** [deric/puppet-zookeeper#22]
I'm getting a failure when installing zookeeper along with zookeeper-service and setting "initialize_datastore" to "true". It seems that puppet is trying to start the service before the initialization has run.   

I believe the reason is that "initialize_datastore" step relies on the absense of ${datastore}/myid, but that is already created earlier in the process. Modifying this step to the following seems to work:

    # Initialize the datastore if required
    if $initialize_datastore {
      exec { 'initialize_datastore':
        command => "/usr/bin/zookeeper-server-initialize --myid=${id}",
        user    => $user,
        creates => "${datastore}/version-2",
        require => File[$datastore],
      }
    }

See Pull Request #23

**Comment by deric** [comment]
Resolved by merging #23.
