### ISSUE TITLE
myid not managed at all

### ISSUE THREAD

**Issue by isotopp** [deric/puppet-zookeeper#27]
https://github.com/deric/puppet-zookeeper/blob/master/templates/conf/zoo.cfg.erb#L30 generates lines of the form server.i with i counting up. Unless the i is also synchronized with the content of the servers myid file this is never generating a runnable configuration at all - the i in server.i and the content of the myid file need to be identical at all times.

So the approach documented in https://github.com/deric/puppet-zookeeper/#cluster-setup can only generate a valid configuration when you manually keep the order of ip numbers in "  servers => ['192.168.1.1', '192.168.1.2', '192.168.1.3']" and the myids specified as zookeeper::id in hiera/host/$hostname synchronized. This is a very poor approach.

Also, you may never insert an ip into the servers array, you can only append at the moment. Not very helpful.

**Comment by isotopp** [comment]
http://zookeeper.apache.org/doc/r3.4.5/zookeeperAdmin.html#sc_clusterOptions

----
server.x=[hostname]:nnnnn[:nnnnn], etc

servers making up the ZooKeeper ensemble. When the server starts up, it determines which server it is by looking for the file myid in the data directory. That file contains the server number, in ASCII, and it should match x in server.x in the left hand side of this setting.
----

**Comment by isotopp** [comment]
On approach is to declare the ensemble part of the zookeeper ensemble as a single structure

    ensemble:
      cloud10:
        ip: 1.2.3.4
        leader-port: 2888
        election-port: 3888
        myid: 1
      cloud11:
        ip: 2.3.4.5
        leader-port: 2888
        election-port: 3888
        myid: 2
      cloud12:
        ip: 3.4.5.6
        leader-port: 2888
        election-port: 3888
        myid: 3
      backup:
        ip: 10.11.12.13
        leader-port: 2888
        election-port: 3888
        myid: 4
        observer: true

resulting in a hiera result of

    {"cloud10"=>
      {"ip"=>"1.2.3.4", "leader-port"=>2888, "election-port"=>3888, "myid"=>1},
     "cloud11"=>
      {"ip"=>"2.3.4.5", "leader-port"=>2888, "election-port"=>3888, "myid"=>2},
     "cloud12"=>
      {"ip"=>"3.4.5.6", "leader-port"=>2888, "election-port"=>3888, "myid"=>3},
     "backup"=>
      {"ip"=>"10.11.12.13",
       "leader-port"=>2888,
       "election-port"=>3888,
       "myid"=>4,
       "observer"=>true}}

**Comment by isotopp** [comment]
The other approach is exported ressources and stages, because you need to collect everything first and only then can generate a server-section of a zoo.cfg. This is a lot of added complexity and also a poor approach. I would not choose that.

Puppet is not very well designed to deal with configuration of things that are larger than a single host, it does not do clusters very well.

**Comment by isotopp** [comment]
Rough untested sketch in https://github.com/isotopp/puppet-zookeeper/commit/b43823ca80d89f669f03bbd9df3fd1d4bb711ee7

**Comment by JayH5** [comment]
A kind of hacky workaround for now if you already have your `servers` array sorted is to do something like this:
```puppet
$servers = ['192.168.0.2', '192.168.0.3', '192.168.0.4']
# Assuming $::ipaddress_eth1 is an element of $servers
$id = inline_template('<%= (@servers.find_index(@ipaddress_eth1) || 0) + 1 %>')
class { 'zookeeper':
  id => $id,
  servers => $servers,
}
```

There could maybe be a properly written/tested function that does this?

**Comment by deric** [comment]
@JayH5  This is quite tricky because we can't be sure which interface is the default one. So, you would need to be able to configure default interface for each server.

**Comment by sterni1971** [comment]
The documentation how to set the "myid" is misleading.  Following the documention I thought

class { 'zookeeper':
  servers => {
    1 => '192.168.1.1',
    2 => '192.168.1.2',
    3 => '192.168.1.3',
  },
}
would also set the myid. 

An example how to use zookeeper class with array would be nice.
And to give the hint that only with array the myid files will be created.

regards!
Sven
