### ISSUE TITLE
Observers documentation wrong

### ISSUE THREAD

**Issue by isotopp** [deric/puppet-zookeeper#28]
In https://github.com/deric/puppet-zookeeper/#observers you say that observers can be listed as 

  observers => ['192.168.1.4', '192.168.1.5']

You do not highlight that observers ALSO need to be listed as "servers". You code does a "if @observers.include? h", though, so observer ips need to be listed twice, as servers and as observers.

**Comment by deric** [comment]
Right, I guess we can simplify it, so that observers will get next number after primary servers. If if won't look too magical.
