### ISSUE TITLE
wrong anchor in os/redhat.pp

### ISSUE THREAD

**Issue by EslamElHusseiny** [deric/puppet-zookeeper#34]
I got this error message : 
`Error: Could not find dependent Anchor[zookeeper::os::debian::java] for Package[java-1.7.0-openjdk]`
while I'm using CentOS.
so this commit https://github.com/deric/puppet-zookeeper/commit/3e62bedfe028066f78be290acd4e9decd7f8ca6b  needs to be added to tag [v0.3.9](https://github.com/deric/puppet-zookeeper/tree/v0.3.9) and [v0.3.8](https://github.com/deric/puppet-zookeeper/tree/v0.3.8)

**Comment by deric** [comment]
Sorry, looks like I forgot to release the latest version. Could you please try [v0.4.0](https://github.com/deric/puppet-zookeeper/releases/tag/v0.4.0)?

**Comment by EslamElHusseiny** [comment]
Thanks.
