### ISSUE TITLE
Zookeeper maxClientCnxns defaults to 60, not 10, since 3.4.0

### ISSUE THREAD

**Issue by JayH5** [deric/puppet-zookeeper#42]
See https://issues.apache.org/jira/browse/ZOOKEEPER-1030

A client connection limit of 10 is very low and it's quite easy to hit this limit without realising it.

**Comment by JayH5** [comment]
There are a few areas where this module is setting Zookeeper config to things that differ from the default (`clientPortAddress` is another one). It might make sense to leave some of these config values unset rather than to set them to things that the user is not expecting.

**Comment by deric** [comment]
Right, I'm always increasing this number manually. I guess this shouldn't cause any problem even for older versions of ZooKeeper, right?
The client port address is a workaround for a [Facter bug](https://tickets.puppetlabs.com/browse/FACT-380). Did you encounter any problems with this default configuration?

**Comment by JayH5** [comment]
Thanks for the response.

I've been comparing the generated config to the default provided in the Ubuntu 14.04 package. The config there doesn't set `clientPortAddress` or `maxClientCnxns` at all.

For both those parameters my suggestion would be to have them default in the module to `undef` and don't add them to the generated config unless the user specifies them. This way we can rely on Zookeeper's defaults rather than trying to match them all the time.

I get the issue with Facter - I'm not suggesting having the client address be `$::ipaddress` by default. The Zookeeper default is to listen on all interfaces. From the docs: "clientPortAddress... This is optional, by default we bind in such a way that any connection to the clientPort for any address/interface/nic on the server will be accepted." For now I'm setting `clientPortAddress` to `0.0.0.0` to get the same effect.

**Comment by deric** [comment]
Ok, I agree. I've changed the defaults. The puppet module does not know which version of ZooKeeper is currently running on the server. Maybe for some settings it might be useful. Zookeeper does not provide easy to use command for obtaining current version (maybe we could parse output from `echo status | nc zkserver1 2181`). Probably easier would be getting package version from Puppet.

**Comment by JayH5** [comment]
Thanks for making those changes :)
