### ISSUE TITLE
Systemd unit file (zookeeper.service.erb) ignores logging configuration

### ISSUE THREAD

**Issue by eyal-lupu** [deric/puppet-zookeeper#44]
Hi,

zkEnv.sh set the ZOO_LOG4J_PROP environment variable (which in turn can be overridden from the environment file) however zookeeper.service ignores that value as it is hard-coded to:

```
-Dzookeeper.root.logger=INFO,CONSOLE
```

While it should have been:
```
-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}
```

**Comment by deric** [comment]
Closed by #45.
