### ISSUE TITLE
Some styling in configuration file - max and min session timeout

### ISSUE THREAD

**Issue by eyal-lupu** [deric/puppet-zookeeper#46]
current template (zoo.cfg.erb) ignores the case in which maxSessionTimeout and/or minSessionTimeout are not configured. In such case the end of the file will look like:

````
# The minimum session timeout in milliseconds that the server will allow the # client to negotiate. Defaults to 2 times the tickTime.

# The maximum session timeout in milliseconds that the server will allow the # client to negotiate. Defaults to 20 times the tickTime.
````

While there is no error in that it would be much more readable and aligned with other if the actual directive and its default value will be included in the file, as in:
````
#minSessionTimeout=2
````

**Comment by deric** [comment]
Fixed by #45.
