### ISSUE TITLE
/sbin/nologin on Ubuntu

### ISSUE THREAD

**Issue by gytisgreitai** [deric/puppet-zookeeper#50]
esnure_resource 'user' sets shell to /sbin/nologin
But on ubutnu Ubuntu 14.04.3 LTS nologin is located at /usr/sbin/nologin

`dpkg -S /usr/sbin/nologin`
`login: /usr/sbin/nologin`

so it fails when installing zookeeper:

`Error: /Stage[main]/Zookeeper::Install/User[zookeeper]/shell: change from /bin/false to /sbin/nologin failed: Shell /sbin/nologin must exist`

I fixed this by simply symlinking /usr/sbin/nologin to /sbin/nologin

**Comment by deric** [comment]
Thanks for reporting this, the bug was introduced in #49. Guess, we have to find a better way how to handle user accounts.

**Comment by deric** [comment]
For Debian family `/bin/false` will be used now. Please reopen this if the problem persists.
