### ISSUE TITLE
$ensure meaning changed since post_install refactor

### ISSUE THREAD

**Issue by JayH5** [deric/puppet-zookeeper#57]
Since 885efc2 (I think), the `ensure` value passed to the `zookeeper` class doesn't mean the same thing it did. Before, the `ensure` value was only passed to the package (at least on Ubuntu 14.04), which meant you could pass it interesting values such as `installed`, `purged`, `3.4.5+dfsg-1`, etc. This is no longer possible as the `ensure` value is also used for the creation of the zookeeper user/group in `zookeeper::post_install`. The possible values are now limited to `present` and `absent`.

I'd like to be able to specify the `ensure` value *just* for the package as it makes it possible to ensure that a certain version of Zookeeper is installed.

**Comment by deric** [comment]
Thanks for reporting this, I've introduced new parameter `ensure_account` to control user accounts management.

**Comment by JayH5** [comment]
Thanks!

**Comment by deric** [comment]
Released as [0.5.1](https://github.com/deric/puppet-zookeeper/releases/tag/v0.5.1), you can update your version requirement.
