### ISSUE TITLE
Logging not working.

### ISSUE THREAD

**Issue by jdelgado-ntent** [deric/puppet-zookeeper#64]
I did a fresh install of zookeeper using this module and noticed that logging is not working. Looking into the log4j.properties files I see that there are variables being called that are not defined. I checked with the default configuration from Apache and there is a chunk of variables missing from the erb file.

**Comment by deric** [comment]
Which version of ZooKeeper do you use?

**Comment by jdelgado-ntent** [comment]
zookeeper-server-3.4.5

**Comment by jdelgado-ntent** [comment]
This is the chunk missing from the log4j.properties.erb file that is present in a default install from the Apache website:

`# Define some default values that can be overridden by system properties`
`zookeeper.root.logger=INFO, CONSOLE`
`zookeeper.console.threshold=INFO`
`zookeeper.log.dir=.`
`zookeeper.log.file=zookeeper.log`
`zookeeper.log.threshold=DEBUG`
`zookeeper.tracelog.dir=.`
`zookeeper.tracelog.file=zookeeper_trace.log`

**Comment by deric** [comment]
Looks like a change introduced by [this commit - (ZOOKEEPER-980)](https://github.com/apache/zookeeper/commit/f1096674ff4fea2974c12eb24be976c251f329e2). From a brief check I would say it's not a breaking change and it should be backward compatible; i.e. there's no need to distribute different logging configuration for different ZooKeeper versions.

**Comment by jdelgado-ntent** [comment]
It doesn't break zookeeper persay as it will still work with no logging turned on, but the logging itself is definitely broken. Your current log4j.properties.erb references those variables and they aren't defined, leading to blank log files.

Line 7:
`log4j.rootLogger=${zookeeper.root.logger}`
_${zookeeper.root.logger} not defined_

Line 31:
`log4j.appender.ROLLINGFILE.File=${zookeeper.log.dir}/zookeeper.log`
_${zookeeper.log.dir} not defined_

**Comment by deric** [comment]
@jdelgado-ntent I've updated the config. Right now we have different logging defaults:
 * `log.threshold=TRACE` - ZooKeeper: `DEBUG`
 * and `console.threshold` can't be configured via puppet

**Comment by deric** [comment]
Released in [v0.5.5](https://github.com/deric/puppet-zookeeper/releases/tag/v0.5.5).
