### ISSUE TITLE
Different version installed for different OS versions.

### ISSUE THREAD

**Issue by JoeBmc** [deric/puppet-zookeeper#65]
Hi Deric,

I am working on Vagrant with puppet for zookeeper installation.

While on Ubuntu-14.04 the zookeeper version that got installed was 3.4.5, but the version installed on Ubuntu-12.04 was 3.3.5.

I needed to use zookeeper version above 3.4. Do we have a way to specify the same.
And why the zookeeper versions are different on different OS version, even though I did not specify the version explicitly.

Images used on vagrant:
  * `puppetlabs/ubuntu-12.04-64-puppet`
  * `puppetlabs/ubuntu-14.04-64-puppet`

```ruby
config.vm.provision :shell do |shell|
			shell.inline = "puppet module install puppetlabs-apt;
					puppet module install deric-zookeeper;
					exit 0"
```
Puppet configuration:
```puppet
exec { 'update-apt-packages':
		command => '/usr/bin/apt-get update -y',
	}
class { 'zookeeper':		
		client_ip => $::ipaddress_lo,		
		require => Exec['update-apt-packages']		
	}
```
Any help is appreciated. 

regards,
Jose

**Comment by JoeBmc** [comment]
Hi,
It seems to be the issue with the zookeeper package present with the default repository on ubuntu-12.04.
ensure => '3.4.6' & ensure => 'latest' did not work.

Do we have a way to point to 'universe' repository to get the latest zookeeper version.

regards,
Jose

**Comment by deric** [comment]
Hi Jose,

you have following packages in Ubuntu:

* 12.04: [zookeeper **3.3.5**](http://packages.ubuntu.com/precise/zookeeper)
* 14.04: [zookeeper **3.4.5**](http://packages.ubuntu.com/trusty/zookeeper)
* 15.10: [zookeeper **3.4.6**](http://packages.ubuntu.com/wily/zookeeper)

If you want to install different version you can compile you own package and upload it to your repository. I'm not aware of any public repository with multiple versions of ZooKeeper for each distribution. ZooKeeper depends mainly on Java, so even installing package from newer distribution might work.

**Comment by JoeBmc** [comment]
Hi Deric,
Thanks for your reply.

Can you please elaborate on -
If you want to install different version you can compile you own package and upload it to your repository.

How to get newer version on Zookeeper on ubuntu 12.04 using puppet. Is there a way I can specify which yum repository to point to while downloading zookeeper.

regards,
Jose

**Comment by deric** [comment]
For Ubuntu you would need to setup an `apt` repository (not `yum`). Currently this module does not support configuration of an `apt` (we can add it, no problem). You should install `puppetlabs-apt` module:
```
puppet module install puppetlabs-apt
``` 
and include an `apt::source` in definition of your zookeeper node
```puppet
  apt::source { 'myrepo':
    location => 'http://apt.example.com',
    release  => "${::lsbdistcodename}",
    repos    => 'main',
    key      => {
      'id'     => 'AAABBB',
      'server' => 'http://apt.example.com',
    },
    include  => {
      'src' => false
    },
  }
```
Once you upload all packages needed to your repository (at least `zookeeper`, `libzookeeper-java`) you should be able to configure zookeeper:
```puppet
class{'zookeeper':
  ensure => '3.4.6-8',
  require => Apt::Source['myrepo'],
}
```

**Comment by JoeBmc** [comment]
Thankyou. Closing the ticket.
