### ISSUE TITLE
manage_service not working set to false

### ISSUE THREAD

**Issue by mativillagra** [deric/puppet-zookeeper#66]
Hello Team, 

I'm installing this module to a docker container OS Centro 7, so I used  `repo   => 'cloudera', cdhver => '5',`  

But I want to set `manage_service => false`, so zookeeper the service is not started when installing the module. 

My code look like this . 

```puppet
class { 'zookeeper':
     	repo => 'cloudera',
     	cdhver => '5',
     	packages => ['zookeeper', 'zookeeper-server'],
     	manage_service => false,
 }
```

Getting this when doing so . 
```
Warning: Could not find resource 'Class[Zookeeper::Service]' in parameter 'notify'
   (at /tmp/puppet/modules/zookeeper/manifests/config.pp:115)
Notice: Compiled catalog for f77e60ad5dfc.personal.corp in environment production in 1.39 seconds
Debug: Creating default schedules
Error: Could not find dependent Class[Zookeeper::Service] for File[/etc/zookeeper/conf/myid] at /tmp/puppet/modules/zookeeper/manifests/config.pp:108
```
Not sure if it is a bug. But I also read that the default is set to true (so puppet will ensure that the service is running).

**Comment by deric** [comment]
Which Puppet version do you use? How did you install the module? Could you check that there is `/tmp/puppet/modules/zookeeper/manifests/service.pp` file in your container?

**Comment by deric** [comment]
I think I found the problem. We're notifying service at point when it's not configured yet (at least during first run). Should be fixed in master branch (I'll try to release new version soon).

**Comment by deric** [comment]
I've tagged new version, but forgeapi seems to be down :(

```
Uploading to Puppet Forge deric/zookeeper
rake aborted!
Blacksmith::Error: Error uploading /home/deric/dev/puppet/puppet-zookeeper/pkg/deric-zookeeper-0.5.5.tar.gz to the forge https://forgeapi.puppetlabs.com [500 Internal Server Error]: {
    "errors": ["500 Server Error"]
}

RestClient::InternalServerError: 500 Internal Server Error
```
so right now it's only on github.

**Comment by mativillagra** [comment]
@deric Thanks for he respond. 

I install the module from a Puppetfile as mod "deric/zookeeper", '0.5.4' then I do librarian-puppet install --verbose, on the hosted system; librarian-puppet (2.2.1).  Puppet version on the Centos 7 (docker container) is 4.5.0. I run puppet through puppet apply inside the docker container.  

Yes, the service.pp file is found at /tmp/puppet/modules/zookeeper/manifests/

[user@laptop manifests]$ ls 
config.pp  init.pp  install.pp  os  params.pp  post_install.pp  repo.pp  **service.pp**

I change the Puppetfile to 

mod "deric/zookeeper",
:git => "https://github.com/deric/puppet-zookeeper.git"

Now the manage_service => false, works! No error is shown. 

Thanks in advance.

**Comment by deric** [comment]
Ok, cool. Finally I've managed to push [v0.5.5](https://github.com/deric/puppet-zookeeper/releases/tag/v0.5.5) to forge.
