### ISSUE TITLE
Template zookeeper.init.erb pidfile not being complete pidfile line 

### ISSUE THREAD

**Issue by mativillagra** [deric/puppet-zookeeper#71]
Hello, I'm using this module with 

```
librarian-puppet (1.5.0) 
puppet --version
3.8.2
ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
```

Install goes well `rpm -qa | grep zookeeper-server zookeeper-server-3.4.5+cdh5.8.0+94-1.cdh5.8.0.p0.76.el6.x86_64` is a Red Hat Enterprise Linux Server release 6.4 version, but when looking at file `/etc/init.d/zookeeper-server` file on line 28 I noticed a blank line like this 
```
pidfile=
```
I see you are passing the template `pidfile=<%= @pid_path %>` the value should be 
```
pidfile="/var/run/$prog.pid"
```
Here is the manifest . 

```puppet
class { 'zookeeper':
      repo => 'cloudera',
      cdhver => '5',
      packages => ['zookeeper', 'zookeeper-server'],
      manage_service => true,
      service_provider => 'init',
      manage_service_file => true,
      require => Class['jdk_oracle']
    }
```
Thanks for your help.

**Comment by deric** [comment]
@mativillagra have you tried passing directly the desired value? like:
```puppet
class { 'zookeeper':
  pid_file => '/var/run/$prog.pid',
  #...
}
```
We don't test the code against ruby 1.8.7 as most of ruby gems are not compatible (moreover 1.8.7 maintenance [has ended in 2014](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/)).

**Comment by deric** [comment]
Fixed in [0.6.0](https://github.com/deric/puppet-zookeeper/releases/tag/v0.6.0).

**Comment by mativillagra** [comment]
Thanks for your quick reply. As you mention yes I know that ruby 1.8.7 is old and outdated (thanks for the provided URL), although Red Hat Enterprise Linux Server release 6.4 comes with that version on their packages managers. 

Anyway I change my Puppetfile to mod 'deric/zookeeper', '0.6.0' (no changes on the manifests some as above), now when I try to provision the hosts with that module, I get 

[10.0.15.22] out: Error: Failed to parse template zookeeper/conf/zoo.cfg.erb:
[10.0.15.22] out:   Filepath: /home/provision/puppet/modules/zookeeper/templates/conf/zoo.cfg.erb
[10.0.15.22] out:   Line: 37
[10.0.15.22] out:   Detail: undefined method `with_index' for []:Array
[10.0.15.22] out:  at /home/provision/puppet/modules/zookeeper/manifests/config.pp:124 on node nintendo.arg.com.ar
[10.0.15.22] out: Error: Failed to parse template zookeeper/conf/zoo.cfg.erb:
[10.0.15.22] out:   Filepath: /home/provision/puppet/modules/zookeeper/templates/conf/zoo.cfg.erb
[10.0.15.22] out:   Line: 37
[10.0.15.22] out:   Detail: undefined method `with_index' for []:Array
[10.0.15.22] out:  at /home/provision/puppet/modules/zookeeper/manifests/config.pp:124 on node nintendo.arg.com.ar

I lookup at the template zookeeper/conf/zoo.cfg.erb on your github repo last change was a month ago.

So let me ask, has the release 0.6.0 has ended complete the support for this puppet module (puppet-zookeeper) to be compatible with Ruby 1.8 

Thanks in advance.

**Comment by deric** [comment]
@mativillagra All the test code is no longer compatible with 1.8.7, which doesn't mean that the module itself won't be compatible. It's just time consuming to maintain code against old Ruby version.

We try to support versions that can be [automatically tested](https://travis-ci.org/deric/puppet-zookeeper), Ruby 1.8.7 was removed from testing matrix in 0.4, with later versions the support is not guaranteed.

**Comment by deric** [comment]
Regarding the error message, the `with_index` method [was indeed introduced in 1.9.3](http://apidock.com/ruby/Enumerator/with_index), but it's just syntactic sugar. It shouldn't be problem to rewrite this part.
