### ISSUE TITLE
Partial Ruby 1.8.7 support

### ISSUE THREAD

**Issue by deric** [deric/puppet-zookeeper#72]
Although 1.8.7 is long past its end of life it seems to be still used (see #71). 8a9d83771adb76d38a027e4e7191d18dae6980ab uses `with_index` method that was [introduced in 1.9.3](http://apidock.com/ruby/v1_9_3_125/Enumerator/with_index).

**Comment by deric** [comment]
@mativillagra could you test the version from master branch?

**Comment by mativillagra** [comment]
@deric 

Confirm that looking at the master branch, makes the module works with 

ruby 1.8.7
librarian-puppet (1.5.0)
puppet version 3.8.5 

file = etc/init.d/zookeeper-server get filled with pidfile=/var/run/zookeeper.pid 

Thanks for the commit / fix.

Al thought let me ask, if the template (templates/conf/zoo.cfg.erb) commit was a month old , what else was changed to stop working at release v0.6.0 . 

Thanks.

**Comment by deric** [comment]
That seems to be the only incompatible part (from the Puppet/Ruby code). You won't be able to run the test, but otherwise it might work.
