### ISSUE TITLE
Zookeeper logging doesn't work

### ISSUE THREAD

**Issue by jomach** [deric/puppet-zookeeper#76]
Hi, So I installed the puppet module and I have this : 

``` puppet
class { 'zookeeper':
          election_port => 2889,
          leader_port   => 3889,
          servers       => {
            1 => '10.0.1.2',
            2 => '10.0.1.3',
            3 => '10.0.1.4',
          },
        }
```

Everything gets installed but then it does not start and I don´t get any log files. I´m on Ubuntu 16.04.1 LTS How Can I debug this ?

**Comment by deric** [comment]
What does `service zookeeper status` output? Have you checked `tail /var/log/zookeeper/zookeeper.log`? Or Ubuntu ships ZooKeeper with full systemd integration and logs goes to `journalctl -u zookeeper`

**Comment by rrada** [comment]
@jomach we've been experiencing the same behaviour with logging on `16.04`, but the zookeeper process was normally running. Try to add `rollingfile_threshold => 'INFO',` to your `zookeeper` class definition. Default for this module is `ERROR`.

**Comment by deric** [comment]
Latest change to logging configuration has been made in #64. I've updated the configuration but default level stayed at `ERROR`. [ZooKeeper default](https://github.com/apache/zookeeper/blob/master/conf/log4j.properties#L26) is `INFO`. It shouldn't be a breaking change, but I would rather include it in `v0.7` release.

**Comment by deric** [comment]
Should be fixed in master branch, I've added `console_threshold` parameter in order to adjust also console logging. I'll try to release the `v0.7`, but it requires some testing with so many changes.
