### ISSUE TITLE
Parameterize the environment variables file

### ISSUE THREAD

**Issue by cristifalcas** [deric/puppet-zookeeper#81]
The official zookeeper scripts load configuration environment variables from [zkEnv.sh](https://github.com/apache/zookeeper/blob/master/bin/zkEnv.sh#L63).

This module writes the configuration to `"${::zookeeper::cfg_dir}/environment"`.

I want to ask if a PR that makes this configurable via a parameter will be accepted.

Thank you

**Comment by deric** [comment]
Sure, sourcing `"${::zookeeper::cfg_dir}/environment"` might be Debian specific. It looks that ZooKeeper is sourcing `java.env` file since version 3.4.0.

**Comment by deric** [comment]
Resolved by #82.
