### ISSUE TITLE
Using Puppet Enterprise, unable to set rollingfile_threshold

### ISSUE THREAD

**Issue by cwneal** [deric/puppet-zookeeper#83]
Hi.

I'm using PE 2016.4, and including your Zookeeper module.  I've set the `rollingfile_threshold` to `"INFO"`, but for some reason, this parameter change never gets propagated through to the .erb file for the log4j.properties definition.  

I've read through the Puppet code, and it looks perfectly correct.  No idea why it isn't working for me.

For now, I've just modified the init.pp file to default to 'INFO' instead of 'ERROR', but obviously this is not an ideal solution.  :)  Any idea why this might be happening?

Thanks!
Chris

**Comment by deric** [comment]
@cwneal could you post the way how you configure ZooKeeper? Are you using Puppet code or Hiera?

**Comment by cwneal** [comment]
@deric All the configuration is done directly via the Puppet Enterprise GUI for the Zookeeper classification.  Please see the attachment.  I guess this ends up as puppet code at some point :)  I'm using Hiera for setting the "myid" parameter for a cluster setup, so I'll give Hiera a try and see if that makes its way to the config file.

Thanks very much!
Chris
<img width="1239" alt="screen shot 2016-12-05 at 3 58 01 pm" src="https://cloud.githubusercontent.com/assets/5016796/20904145/dcee09ac-bb03-11e6-9c3e-87b9c2d419fb.png">

**Comment by deric** [comment]
@cwneal It looks ok. Which version of `deric-zookeeper` do you use? And what is the underlying OS?

**Comment by cwneal** [comment]
I had downloaded master from github so I could have the customized environment file code :)  Underlying OS is CentOS 6.8.  Haven't had a change to try hiera yet.....I will though.

**Comment by deric** [comment]
It should be the same, Hiera parameters are auto(magically) translated into Puppet class parameters (if correctly used).

All other parameters works well for you? `INFO` is the new default value for `rollingfile_threshold` (at least in master and `v0.7.0`). I'm a bit suspicious, that you're not changing parameters in correct namespace.
