### ISSUE TITLE
Double file declaration of env.java when using SASL on RedHat

### ISSUE THREAD

**Issue by dlanza1** [deric/puppet-zookeeper#89]
Hi guys,

If os family is RedHat, `$environment_file` is assigned to `env.java` in [`params.pp:50`](https://github.com/deric/puppet-zookeeper/blob/master/manifests/params.pp#L50).

Then a double file declaration will be produce if SASL is enabled, one in `file.pp:67` an another one in [`sasl.pp:14`](https://github.com/deric/puppet-zookeeper/blob/master/manifests/sasl.pp#L14).

We have solved the problem assigning `environment` to `$environment_file` in `params.pp:50`.

Cheers,
Daniel

**Comment by deric** [comment]
Thanks for reporting that. By `file.pp:67` you probably mean [config.pp#68](https://github.com/deric/puppet-zookeeper/blob/master/manifests/config.pp#L68), right?

**Comment by dlanza1** [comment]
Yes, sorry.

**Comment by deric** [comment]
@dlanza1 Should be fixed in `master` branch. The `environment` file is handled differently on Debian than on other distributions. It causes quite a lot confusion. Could you verify that it works in your environment?

**Comment by dlanza1** [comment]
@deric We are about to test it, thanks a lot for the fix. We will let you know the result.

Cheers.

**Comment by dlanza1** [comment]
It has been tested and works properly.

Thanks again @deric !

**Comment by deric** [comment]
Good. Glad to hear that.

**Comment by deric** [comment]
[v0.7.1 release](https://github.com/deric/puppet-zookeeper/releases/tag/v0.7.1) is available at forge.
