### ISSUE TITLE
service template should be modified to handle archive based installation

### ISSUE THREAD

**Issue by vinodpattel** [deric/puppet-zookeeper#93]
Zookeeper service template file - zookeeper/templates/zookeeper.service.erb - needs to be modified to handle archived based installation.

I use zookeeper-3.4.9.tar.gz to install zookeeper.

zookeeper.jar file present inside the archive is of the format - zookeeper-3.4.9.jar (instead of the expected, zookeeper.jar). I am not sure if rpm based installation installs with default zookeeper.jar name.

However, the service template file creates zookeeper.service with 'zookeeper.jar' in its classpath. This results in service not coming up, as main jar file is not found.

> CLASSPATH="<%= @_zoo_dir %>/zookeeper.jar

Need to add an additional check, like - If 'install_method' is 'archive', then 

> zookeeper-<%= scope.lookupvar("zookeeper::archive_version") %>.jar

**Comment by vinodpattel** [comment]
I see this is already addressed in master. Closing this issue.

**Comment by deric** [comment]
@vinodpattel Sorry about that, I've tagged [v0.7.2](https://github.com/deric/puppet-zookeeper/releases/tag/v0.7.2) and pushed it to the forge.
