### ISSUE TITLE
How to stop openjdk-8-jre-headless from installing

### ISSUE THREAD

**Issue by witchbutter** [deric/puppet-zookeeper#97]
I have tried many ways to prevent the package `openjdk-8-jre-headless` from installing including setting the parameter `install_java => false` to class ordering to banning the package in Ubuntu, yet somehow invariably the zookeeper class installs it, causes the service to start using this openjdk in a standalone mode and then causes the zookeeper java process to hang.  Only when I manually touch the server and kill the initial standalone process can I restart and have the service use the oracle jdk I have installed.  Why is this?

**Comment by deric** [comment]
I'm not sure that this problem is related to this module. `zookeeper` package in Debian (Ubuntu) specifies dependencies:
```
Package: zookeeper                       
Version: 3.4.9-2
State: not installed
Priority: optional
Section: universe/java
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 188 k
Depends: adduser, default-jre-headless | java6-runtime-headless, libzookeeper-java (= 3.4.9-2)
```
So, when Puppet installs `apt-get install zookeeper` some java from `default-jre-headless` meta package will be selected. If you've already installed different (valid java package) that provides `default-jre-headless`, then it shouldn't happen.

Could you check puppet debug log (`puppet agent -td`) and apt log for more details?

**Comment by witchbutter** [comment]
I was able to prevent the wrong java installation by writing a custom fact to check for my installed Oracle JRE.  This causes successive puppet runs that allow zookeeper to install with the correct JRE.  I could not figure out why this was necessary.

The crashing I was experiencing seems to be due to zookeeper itself, not the jre.  For some reason if you already have a running quorum, in my case 4 servers, and you add one it first starts in standalone mode, then identifies it's id, in my case 5, then promptly hangs so that service cannot restart via systemd because it sees a java process running.  A kill followed by starting the service allows this to correct itself.  This is with 3.4.8 zookeeper provided by Ubuntu 16.04 repos and JRE 8 update 121.
